# gg
algo = input('Digite algo: ')
print('O tipo primitivo do valor É: ?',type(algo))
print('O que voce digitou  É numerico?',algo.isnumeric())
print('O que voce digitou  É alfabetico? ',algo.isalpha())
print('O que voce digitou  É Decimal?',algo.isdecimal())
print('O que voce digitou  É alfanumerico?',algo.isalnum())
print('O que voce digitou  So tem espaço?',algo.isspace())
print('O que voce digitou  Esta em maiuscula?',algo.isupper())
print('O que voce digitou  Esta em minuscula?',algo.islower())
print('O que voce digitou  Esta capitalizada?',algo.istitle())
